aramis-lab/leaspy

- .gitlab-ci.yml
Also test integration of read the docs.
> [CI] Remove doc build from gitlab CI

- src/leaspy/algo/base.py
This PR updates docstrings of algo/base related to issue #122 .
> clean docstrings of algo base

- src/leaspy/algo/base.py
- src/leaspy/api.py
This PR removes remaining `return_loss` from the functions and docs.
> remove return loss

- src/leaspy/models/utilities.py
This PR updates docstrings of models/utilities files as it is mentioned in issue https://github.com/aramis-lab/leaspy/issues/122.
> Clean docstring of utilities

- src/leaspy/utils/weighted_tensor/_weighted_tensor.py
This PR updates docstrings of weighted_tensor/weighted_tensor files as it is mentioned in issue https://github.com/aramis-lab/leaspy/issues/122.
Also modify reverse function, where the reverse argument wasn't present before.
> Update docstring weighted_tensor

- src/leaspy/algo/personalize/abstract_mcmc_personalize.py
- tests/functional_tests/api/test_api_personalize.py
Following #371 addressing forgotten bits of #334
> Clean dirty hacks 2

- docs/index.md
- docs/mathematics.md
- docs/notations.md
Just trying something in plain Markdown to see how it renders and whether it can be of any help for us...
> Add notations page

- src/leaspy/samplers/base.py
- src/leaspy/samplers/factory.py
- src/leaspy/samplers/gibbs.py
This PR is related to issue #122 and improves docs of files in `leaspy/samplers`
> Docstring samplers

- docs/install.md
- examples/plot_quickstart.py
- src/leaspy/models/abstract_model.py
This PR shows how to add some of these block at different places of the documentation in order to make things clearer and prettier.
> Add some examples of warning, tip, and note blocks

- Makefile
- docs/conf.py
- docs/index.md
- examples/plot_quickstart.py
Improve small details related to docs.
> Improve documentation configuration

- src/leaspy/algo/base.py
- src/leaspy/algo/fit/abstract_fit_algo.py
- src/leaspy/algo/personalize/abstract_personalize_algo.py
- src/leaspy/models/__init__.py
> Fix inheritance issues for algorithm methods `run` and `run_impl`

- docs/sg_execution_times.rst
- src/leaspy/io/data/individual_data.py
- src/leaspy/models/stateful.py
Clean docstrings of models.stateful.py and data.individual_data.py as discussed in issue https://github.com/aramis-lab/leaspy/issues/122
> Cleaning docstring individual_data and stateful

- src/leaspy/models/obs_models/_base.py
- src/leaspy/models/obs_models/_bernoulli.py
- src/leaspy/models/obs_models/_gaussian.py
Clean and complete the docstrings in obs_models as mentioned at issue #122
> Clean and complete docstrings in obs_models

- CHANGELOG.md
- pyproject.toml
> prepare rc2

- src/leaspy/io/data/factory.py
Add and complete the docstrings in io/data/factory.py as mentioned in issue https://github.com/aramis-lab/leaspy/issues/122
> Add docstrings data/factory.py

- src/leaspy/io/outputs/result.py
Add and complete the docstings in io.outputs.result.py as mentioned in issue #122
> Clean docstrings io.outputs.result.py

- src/leaspy/datasets/loader.py
- src/leaspy/io/data/dataset.py
Add and complete the docstrings in io/data/dataset.py and datasets/loader.py as mentioned in issue https://github.com/aramis-lab/leaspy/issues/122
> Clean docstring data.dataset.py and dataset/loader.py

- src/leaspy/models/settings.py
Add and complete the docstrings in models/settings.py as mentioned in issue https://github.com/aramis-lab/leaspy/issues/122
> Cleaning docstrings settings

- README.md
This PR adds new support information to Readme.
> add support

- README.md
This PR updates git clone link in the readme.
> fix_gitlab

- src/leaspy/variables/dag.py
- src/leaspy/variables/distributions.py
- src/leaspy/variables/specs.py
- src/leaspy/variables/state.py
- src/leaspy/variables/utilities.py
Clean and complete the docstrings in the variables module as mentioned in issue #122
> New PR to clean and update docstrings of variables module

- docs/sg_execution_times.rst
- src/leaspy/io/logs/visualization/plotter.py
This PR improves docstrings of `plotter` file and it is related to issue #122.
> clean docs plotter

- docs/sg_execution_times.rst
- src/leaspy/io/logs/visualization/plotting.py
This PR improves plotting file docs.
> improve plotting docs

- docs/sg_execution_times.rst
- src/leaspy/utils/distributions.py
- src/leaspy/utils/filtered_mapping_proxy.py
- src/leaspy/utils/linalg.py
This PR improves docstrings of remaining files in `utils` directory.
> improve docs

- CHANGELOG.md
- pyproject.toml
This PR includes small changes for release.
> prepare release
